# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [160]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [161]:
# Create a 1-dimensional NumPy array using np.array()

dimensional_1=np.array([1 , 2 , 3 , 4 , 5])
# Create a 2-dimensional NumPy array using np.array()

dimensional_2= np.array([[1 , 2 , 3] , [4 , 5 , 6]])
# Create a 3-dimensional Numpy array using np.array()
dimensional_3= np.array([[[1,2] ,[3,4]] , [[5 , 6] ,[7 ,8]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [162]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
shape = dimensional_1.shape
number_of_dim = dimensional_1.ndim
data_type = dimensional_1.dtype
size = dimensional_1.size
type_ = type(dimensional_1)


print("shape {}  ,number of dimensions {} , data_type {} , size {} , type {}  ".format(shape , number_of_dim , data_type , size , type_))


shape (5,)  ,number of dimensions 1 , data_type int32 , size 5 , type <class 'numpy.ndarray'>  


In [163]:
# Attributes of 2-dimensional array
shape = dimensional_2.shape
number_of_dim = dimensional_2.ndim
data_type = dimensional_2.dtype
size = dimensional_2.size
type_ = type(dimensional_2)


print("shape {}  ,number of dimensions {} , data_type {} , size {} , type {}  ".format(shape , number_of_dim , data_type , size , type_))


shape (2, 3)  ,number of dimensions 2 , data_type int32 , size 6 , type <class 'numpy.ndarray'>  


In [164]:
# Attributes of 3-dimensional array
shape = dimensional_3.shape
number_of_dim = dimensional_3.ndim
data_type = dimensional_3.dtype
size = dimensional_3.size
type_ = type(dimensional_3)


print("shape {}  ,number of dimensions {} , data_type {} , size {} , type {}  ".format(shape , number_of_dim , data_type , size , type_))


shape (2, 2, 2)  ,number of dimensions 3 , data_type int32 , size 8 , type <class 'numpy.ndarray'>  


In [165]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

pd.DataFrame (dimensional_2 )


0  1  2
0  1  2  3
1  4  5  6

In [166]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [167]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7 , 2 ,3))


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [168]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [169]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0, 11, size=(7, 2))


array([[ 7, 10],
       [ 0,  5],
       [ 7,  4],
       [ 3,  1],
       [ 5,  5],
       [10,  0],
       [ 8, 10]])

In [170]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(7 ,2)


array([[0.18651851, 0.04077514],
       [0.59089294, 0.67756436],
       [0.01658783, 0.51209306],
       [0.22649578, 0.64517279],
       [0.17436643, 0.69093774],
       [0.38673535, 0.93672999],
       [0.13752094, 0.34106635]])

In [171]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 11, size=(4, 6))


array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [172]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

array_Rand = np.random.randint(0 , 11 , size=( 3 , 7) )
# Find the unique numbers in the array you just created
np.unique(array_Rand)


array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10])

In [173]:
# Find the 0'th index of the latest array you created
array_Rand[0 , 0]

0

In [174]:
# Get the first 2 rows of latest array you created
array_Rand[:2 , :]


array([[ 0,  9,  5,  8,  0, 10, 10],
       [ 9,  2,  6,  3,  8,  2,  4]])

In [175]:
# Get the first 2 values of the first 2 rows of the latest array
array_Rand[:2 , : 2]


array([[0, 9],
       [9, 2]])

In [176]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.uniform(0, 10, (3, 5))

# Create an array of ones with size (3, 5)
ones_array = np.ones((3, 5))

In [177]:
# Add the two arrays together
np.add(random_array ,ones_array )


array([[10.42201756,  6.63288218,  4.85416503,  1.15966252,  3.30893826],
       [ 3.41025466,  7.83263519,  7.09996658,  9.33194912,  2.73364654],
       [ 4.91060608,  2.82236088,  8.5536141 ,  5.25155874,  3.07941663]])

In [178]:
# Create another array of ones of shape (5, 3)
ones_array_2=np.ones((3 , 5))

In [179]:
# Try add the array of ones and the other most recent array together
np.add(ones_array_2 , np.add(random_array ,ones_array ))


array([[11.42201756,  7.63288218,  5.85416503,  2.15966252,  4.30893826],
       [ 4.41025466,  8.83263519,  8.09996658, 10.33194912,  3.73364654],
       [ 5.91060608,  3.82236088,  9.5536141 ,  6.25155874,  4.07941663]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [180]:
# Create another array of ones of shape (3, 5)
ones_array_3= np.ones((3,5))


In [181]:
# Subtract the new array of ones from the other most recent array
subtract = np.subtract( np.add(random_array ,ones_array ) ,ones_array_3 )


In [182]:
# Multiply the ones array with the latest array
np.multiply ( random_array ,ones_array_3 )

array([[9.42201756, 5.63288218, 3.85416503, 0.15966252, 2.30893826],
       [2.41025466, 6.83263519, 6.09996658, 8.33194912, 1.73364654],
       [3.91060608, 1.82236088, 7.5536141 , 4.25155874, 2.07941663]])

In [183]:
# Take the latest array to the power of 2 using '**'

random_array**2

array([[8.87744148e+01, 3.17293616e+01, 1.48545880e+01, 2.54921210e-02,
        5.33119587e+00],
       [5.80932753e+00, 4.66849036e+01, 3.72095923e+01, 6.94213761e+01,
        3.00553031e+00],
       [1.52928399e+01, 3.32099917e+00, 5.70570860e+01, 1.80757518e+01,
        4.32397352e+00]])

In [184]:
# Do the same thing with np.square()
np.square(random_array)


array([[8.87744148e+01, 3.17293616e+01, 1.48545880e+01, 2.54921210e-02,
        5.33119587e+00],
       [5.80932753e+00, 4.66849036e+01, 3.72095923e+01, 6.94213761e+01,
        3.00553031e+00],
       [1.52928399e+01, 3.32099917e+00, 5.70570860e+01, 1.80757518e+01,
        4.32397352e+00]])

In [185]:
# Find the mean of the latest array using np.mean()
np.mean(random_array)


4.426911603219391

In [186]:
# Find the maximum of the latest array using np.max()
np.max(random_array)


9.422017556848527

In [187]:
# Find the minimum of the latest array using np.min()
np.min(random_array)



0.15966252220214194

In [188]:
# Find the standard deviation of the latest array

np.std(random_array)

2.670246399546109

In [189]:
# Find the variance of the latest array
np.var(random_array)


7.1302158342889586

In [190]:
# Reshape the latest array to (3, 5, 1)
Reshape= random_array.reshape ((3, 5, 1))

In [191]:
# Transpose the latest array
trans = Reshape.T


What does the transpose do?

In [192]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


random_integers_array_3x3 = np.random.randint(0, 11, size=(3, 3))

random_integers_array_3x2 = np.random.randint(0, 11, size=(3, 2))


In [193]:
# Perform a dot product on the two newest arrays you created
np.dot(random_integers_array_3x3, random_integers_array_3x2)

array([[ 48,  33],
       [112, 127],
       [ 76,  70]])

In [194]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_integers_array_4x3 = np.random.randint(0, 11, size=(4, 3))

random_integers_array_4x3_ = np.random.randint(0, 11, size=(4, 3))


In [195]:
# Perform a dot product on the two newest arrays you created
np.dot(random_integers_array_4x3, random_integers_array_4x3_)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

np.dot(random_integers_array_4x3.T, random_integers_array_4x3_)

array([[108, 160, 156],
       [100, 201, 223],
       [ 36, 109, 134]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random_3x3_1 = np.random.randint(0, 11, size=(3, 3))
random_3x3_2 = np.random.randint(0, 11, size=(3, 3))


In [ ]:
# Compare the two arrays with '>'

random_3x3_1>random_3x3_2

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='
random_3x3_1 >= random_3x3_2


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# Find which elements of the first array are greater than 7
random_3x3_1 > 7


array([[False, False, False],
       [ True, False,  True],
       [False, False,  True]])

In [ ]:
# Which parts of each array are equal? (try using '==')
random_3x3_1 == random_3x3_2

array([[False,  True, False],
       [ True, False, False],
       [False, False, False]])

In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(random_3x3_1)


array([[ 0,  2,  4],
       [ 7,  9, 10],
       [ 5,  7,  8]])

In [ ]:
# Sort the indexes of one of the arrays you just created
np.argsort(random_3x3_1 ,axis=None)



array([1, 2, 0, 6, 4, 7, 8, 3, 5], dtype=int64)

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(random_3x3_1)

5

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(random_3x3_1)


1

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(random_3x3_1 , axis=1)


array([0, 2, 2], dtype=int64)

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(random_3x3_1 , axis=0)


array([0, 0, 0], dtype=int64)

In [ ]:
# Create an array of normally distributed random numbers
np.random.normal(0, 1, size=(3 , 3))

array([[-0.44176602, -0.08416509,  1.23701607],
       [-1.42647888,  0.33802266,  1.9745712 ],
       [ 1.96503476, -1.93991122, -0.76262696]])

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.